# Import third party packages.
import numpy as np
import pandas as pd

# Import local packages.
from src.engines.backtest_engine import BacktestEngine
from src.models.backtest_result import BacktestResult
from src.models.trade import Trade


class BacktestService:
    """
    Coordinates backtesting operations and generates performance reports.

    This service delegates trade execution to the BacktestEngine and is
    responsible for validating inputs, calculating performance metrics, and
    constructing the final BacktestResult model.
    """

    def serve_backtest(
        self,
        ticker: str,
        data: pd.DataFrame,
        signals: pd.DataFrame,
        initial_capital: float = 10_000.0,
    ) -> BacktestResult | None:
        """
        Run a signal-driven backtest.

        Args:
            ticker: Stock ticker symbol being tested.
            data: Historical OHLCV market data.
            signals: Generated buy/sell signals.
            initial_capital: Starting portfolio value.

        Returns:
            BacktestResult containing performance metrics, executed trades,
            and equity curve, or None if the input data is invalid.
        """
        if not self._validate_input(data, signals):
            return None

        engine = BacktestEngine(
            ticker=ticker,
            initial_capital=initial_capital,
        )

        trades, equity_curve = engine.run(
            data=data,
            signals=signals,
        )

        return BacktestResult(
            total_return=self._calculate_total_return(
                equity_curve,
                initial_capital,
            ),
            buy_hold_return=self._calculate_buy_hold_return(
                data,
            ),
            sharpe_ratio=self._calculate_sharpe_ratio(
                equity_curve,
            ),
            max_drawdown=self._calculate_max_drawdown(
                equity_curve,
            ),
            win_rate=self._calculate_win_rate(
                trades,
            ),
            num_trades=len(trades),
            trades=trades,
            equity_curve=equity_curve,
        )

    @staticmethod
    def _validate_input(
        data: pd.DataFrame,
        signals: pd.DataFrame,
    ) -> bool:
        """
        Validate required backtest inputs.

        Returns:
            True if both datasets are valid, otherwise False.
        """
        return (
            data is not None
            and not data.empty
            and signals is not None
            and not signals.empty
        )

    @staticmethod
    def _calculate_total_return(
        equity_curve: pd.DataFrame,
        initial_capital: float,
    ) -> float:
        """
        Calculate the percentage return generated by the strategy.
        """
        final_value = float(equity_curve["Portfolio"].iloc[-1])

        return (final_value - initial_capital) / initial_capital * 100

    @staticmethod
    def _calculate_buy_hold_return(
        data: pd.DataFrame,
    ) -> float:
        """
        Calculate the return of a passive buy-and-hold strategy.
        """
        close = data["Close"].dropna()

        if close.empty:
            return 0.0

        first_price = float(close.iloc[0])
        final_price = float(close.iloc[-1])

        if first_price == 0:
            return 0.0

        return (final_price - first_price) / first_price * 100

    @staticmethod
    def _calculate_max_drawdown(
        equity_curve: pd.DataFrame,
    ) -> float:
        """
        Calculate the largest portfolio decline from a previous peak.
        """
        portfolio = equity_curve["Portfolio"]

        rolling_max = portfolio.cummax()

        drawdown = (portfolio - rolling_max) / rolling_max * 100

        return float(drawdown.min())

    @staticmethod
    def _calculate_sharpe_ratio(
        equity_curve: pd.DataFrame,
    ) -> float:
        """
        Calculate annualized Sharpe ratio.

        Assumes:
            - 252 trading days per year.
            - Zero risk-free rate.
        """
        portfolio = equity_curve["Portfolio"]

        daily_returns = portfolio.pct_change().dropna()

        if daily_returns.empty:
            return 0.0

        volatility = daily_returns.std()

        if volatility == 0:
            return 0.0

        return float((daily_returns.mean() / volatility) * np.sqrt(252))

    @staticmethod
    def _calculate_win_rate(
        trades: list[Trade],
    ) -> float:
        """
        Calculate the percentage of profitable trades.
        """
        if not trades:
            return 0.0

        winning_trades = sum(1 for trade in trades if trade.pnl > 0)

        return winning_trades / len(trades) * 100
