# Import standard library packages.
from datetime import datetime

# Import third party packages.
from pydantic import BaseModel


class Trade(BaseModel):
    """
    Represents a completed trade executed during a backtesting simulation.

    Attributes:
        ticker: Stock ticker symbol associated with the trade.
        entry_date: Timestamp when the position was opened.
        exit_date: Timestamp when the position was closed.
        entry_price: Asset price at the time of entry.
        exit_price: Asset price at the time of exit.
        pnl: Absolute profit or loss generated by the trade.
        return_pct: Percentage return generated by the trade.
    """

    ticker: str
    entry_date: datetime
    exit_date: datetime
    entry_price: float
    exit_price: float
    pnl: float
    return_pct: float
